// build_tsugi.mjs : generate tsugi_verify.mjs, the single-file, zero-dependency verifier for TSUGI recovery chains
// (recovery-v0: drift, proposal, authorization, execution, verify; the random witness draw and its quorum; the
// v2.2 commit-then-reveal check), by concatenating the pinned modules in dependency order and stripping internal
// imports and the CLI block of witness_draw. Deterministic: same sources, same bytes. The committed tsugi_verify.mjs
// is the artifact; tsugi_verify.test.mjs refuses when the artifact is not what this build produces.
import { readFileSync, writeFileSync } from "node:fs";

const SOURCES = [
  "../agreement-v0/agreement_canonical.mjs",
  "../recovery-v0/recovery_schema.mjs",
  "../recovery-v0/witness_draw.mjs",
  "../recovery-v0/recovery_verify.mjs",
];

const PRELUDE = `#!/usr/bin/env node
// tsugi_verify.mjs : single-file, zero-dependency verifier for a TSUGI recovery chain (HORIZON SHIELD, second pillar).
//
// GENERATED by build_tsugi.mjs from the pinned recovery-v0 modules. Do not edit by hand; edit the sources and rebuild.
// Zero external dependencies: only Node built-ins (WebCrypto for SHA-256 and Ed25519). Copy this one file into your
// project and verify a recovery chain yourself, offline, with no trust in the operator:
//
//   node tsugi_verify.mjs chain.json                                  # lenient: hashes, links, order, catalog
//   node tsugi_verify.mjs chain.json --operator-key <b64>             # strict: human-approval repairs need a signed, trusted, unexpired authorization
//   node tsugi_verify.mjs chain.json --operator-key <b64> --pool pool.json --q 2 --k 3 --beacon <block hash> --require-commitment --anchor-height H --anchor-hash <hash>
//   import { verifyChain, verifyRecord, recordSha256, draw, commitmentClaimText, fetchOperatorKeys } from "./tsugi_verify.mjs"
//
// chain.json is either an array of records or an object { records: [...], operator_public_key_ed25519_b64?: "..." }
// (the shape the repository publishes for real incidents). Every record_sha256 recomputes here from the record's
// canonical bytes (keys sorted by code point, separators , and :, non-ASCII unescaped, hash and signature fields
// removed); the authorization's Ed25519 signature is verified over the same bytes; the random witness draw is
// recomputed from beacon, pool and subject; a quorum of drawn, signed, distinct-domain witnesses is counted.
// What a green report does not establish is written into every record's does_not_establish; read it.
import { readFileSync, realpathSync } from "node:fs";
import { fileURLToPath } from "node:url";
if (!globalThis.crypto || !globalThis.crypto.subtle) globalThis.crypto = (await import("node:crypto")).webcrypto;
`;

const EPILOGUE = `
// ---- CLI ----
function tsugiArgs(argv) {
  const a = {}; const pos = [];
  for (let i = 0; i < argv.length; i++) { const x = argv[i]; if (x.startsWith("--")) { const v = argv[i + 1]; if (v !== undefined && !v.startsWith("--")) { a[x.slice(2)] = v; i++; } else a[x.slice(2)] = true; } else pos.push(x); }
  return { a, pos };
}
async function tsugiMain() {
  const { a, pos } = tsugiArgs(process.argv.slice(2));
  const file = pos[0];
  if (!file) { console.error("usage: node tsugi_verify.mjs chain.json [--operator-key <b64> | --fetch-operator-key <origin>] [--pool pool.json --q N --k N --beacon <hash> --require-commitment --anchor-height H --anchor-hash <hash>]"); process.exit(2); }
  const loaded = JSON.parse(readFileSync(file, "utf8"));
  const records = Array.isArray(loaded) ? loaded : loaded.records;
  const opts = {};
  if (a["operator-key"]) opts.operatorKeys = String(a["operator-key"]).split(",").map((s) => s.trim()).filter(Boolean);
  else if (a["fetch-operator-key"]) opts.operatorKeys = await fetchOperatorKeys(a["fetch-operator-key"]);
  else if (!Array.isArray(loaded) && typeof loaded.operator_public_key_ed25519_b64 === "string" && a["trust-embedded-key"]) opts.operatorKeys = [loaded.operator_public_key_ed25519_b64];
  if (a.pool || a.q || a.k || a.beacon || a["require-commitment"] || a["anchor-height"]) {
    opts.witnessQuorum = {};
    if (a.pool) opts.witnessQuorum.pool = JSON.parse(readFileSync(a.pool, "utf8"));
    if (a.q) opts.witnessQuorum.q = Number(a.q);
    if (a.k) opts.witnessQuorum.k = Number(a.k);
    if (a.beacon) opts.witnessQuorum.beaconHash = String(a.beacon);
    if (a["require-commitment"]) opts.witnessQuorum.requireCommitment = true;
    if (a["anchor-height"]) opts.witnessQuorum.commitmentAnchor = { height: String(a["anchor-height"]), ...(a["anchor-hash"] ? { hash: String(a["anchor-hash"]) } : {}) };
  }
  const report = await verifyChain(records, opts);
  const out = { verifier: "tsugi_verify " + VERIFIER_VERSION, mode: { operator_keys: opts.operatorKeys ? opts.operatorKeys.length : 0, witness_quorum: opts.witnessQuorum || null }, ...report,
    note: opts.operatorKeys ? undefined : "lenient: no operator key given, so a chat-approved (unsigned) authorization passes; pass --operator-key or --fetch-operator-key <origin> for strict",
    does_not_establish: ["that any record is true: hashes and signatures prove who wrote what and in which order, not that the observation was correct", "that the repair was the right one: that is the proposal's own does_not_establish", "operator independence of the witness that wrote the drift records: read witness.vantage"] };
  console.log(JSON.stringify(out, null, 2));
  process.exit(report.ok ? 0 : 1);
}
let tsugiIsMain = false;
try { tsugiIsMain = process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url); } catch (e) { tsugiIsMain = false; }
if (tsugiIsMain) await tsugiMain();
`;

let out = PRELUDE;
const aliasLines = [];                                             // "import { draw as drawWitnesses }" survives as "const drawWitnesses = draw;"
const seenConst = new Map();                                       // module-level helpers repeated verbatim across modules (HEX64, enc): keep the first
for (const rel of SOURCES) {
  const src = readFileSync(new URL(rel, import.meta.url), "utf8");
  out += "\n// ============================== " + rel.replace(/^\.\.\//, "") + " ==============================\n";
  let skipping = false;
  for (const line of src.split("\n")) {
    if (/^\/\/ @@CLI_BEGIN/.test(line)) { skipping = true; continue; }
    if (/^\/\/ @@CLI_END/.test(line)) { skipping = false; continue; }
    if (skipping) continue;
    if (/^\s*import\s/.test(line)) {                             // internal imports: everything is in this file; node:fs/url: in the prelude
      const m = line.match(/^\s*import\s*\{([^}]*)\}\s*from\s*["'](\.\.?\/[^"']+)["']/);
      if (m) for (const part of m[1].split(",")) { const am = part.trim().match(/^(\S+)\s+as\s+(\S+)$/); if (am) aliasLines.push("const " + am[2] + " = " + am[1] + ";"); }
      continue;
    }
    if (/^\/\/ RUN_ALL:/.test(line)) continue;
    const cm = line.match(/^const (\w+) = /);
    if (cm) { const prev = seenConst.get(cm[1]); if (prev === line) continue; if (prev !== undefined) throw new Error("const " + cm[1] + " defined differently in two modules; rename one"); seenConst.set(cm[1], line); }
    out += line + "\n";
  }
}
if (aliasLines.length) out += "\n// ---- internal import aliases (restored from stripped aliased imports) ----\n" + [...new Set(aliasLines)].join("\n") + "\n";
out += EPILOGUE;
writeFileSync(new URL("./tsugi_verify.mjs", import.meta.url), out);
console.log("wrote tsugi_verify.mjs (" + out.split("\n").length + " lines) from " + SOURCES.length + " modules");
