#!/usr/bin/env node
// tsugi_verify.mjs : single-file, zero-dependency verifier for a TSUGI recovery chain (HORIZON SHIELD, second pillar).
//
// GENERATED by build_tsugi.mjs from the pinned recovery-v0 modules. Do not edit by hand; edit the sources and rebuild.
// Zero external dependencies: only Node built-ins (WebCrypto for SHA-256 and Ed25519). Copy this one file into your
// project and verify a recovery chain yourself, offline, with no trust in the operator:
//
//   node tsugi_verify.mjs chain.json                                  # lenient: hashes, links, order, catalog
//   node tsugi_verify.mjs chain.json --operator-key <b64>             # strict: human-approval repairs need a signed, trusted, unexpired authorization
//   node tsugi_verify.mjs chain.json --operator-key <b64> --pool pool.json --q 2 --k 3 --beacon <block hash> --require-commitment --anchor-height H --anchor-hash <hash>
//   import { verifyChain, verifyRecord, recordSha256, draw, commitmentClaimText, fetchOperatorKeys } from "./tsugi_verify.mjs"
//
// chain.json is either an array of records or an object { records: [...], operator_public_key_ed25519_b64?: "..." }
// (the shape the repository publishes for real incidents). Every record_sha256 recomputes here from the record's
// canonical bytes (keys sorted by code point, separators , and :, non-ASCII unescaped, hash and signature fields
// removed); the authorization's Ed25519 signature is verified over the same bytes; the random witness draw is
// recomputed from beacon, pool and subject; a quorum of drawn, signed, distinct-domain witnesses is counted.
// What a green report does not establish is written into every record's does_not_establish; read it.
import { readFileSync, realpathSync } from "node:fs";
import { fileURLToPath } from "node:url";
if (!globalThis.crypto || !globalThis.crypto.subtle) globalThis.crypto = (await import("node:crypto")).webcrypto;

// ============================== agreement-v0/agreement_canonical.mjs ==============================
// The canonical byte form, in JavaScript, matching Python's
// json.dumps(obj, sort_keys=True, separators=(",",":"), ensure_ascii=True).
//
// Why this file exists (2026-09-10).
//
// Before any rule of the verifier is written a second time, the two languages
// have to agree on what bytes a record IS. Four places where they do not agree
// unless made to:
//
//   Key order. Python's sort_keys compares strings by code point. JavaScript's
//   default sort compares by UTF-16 code unit. For anything above the BMP those
//   disagree: U+1F600 is D83D DE00 in UTF-16, and D83D sorts below U+FFFD, so
//   the two languages put the same two keys in opposite order. One such key
//   anywhere and every byte after it differs.
//
//   Escaping. Python with ensure_ascii escapes backslash, quote, and every
//   character outside 0x20 to 0x7E, including 0x7F, and writes anything above
//   the BMP as a surrogate pair. JSON.stringify escapes almost nothing.
//
//   Integers. Python's int has no ceiling. JavaScript's number stops being
//   exact at 2^53. The fixture holds 376 copies of 2^70. JSON.parse turns that
//   into 1.1805916207174113e+21 and the record is a different record. So an
//   integer from the wire becomes a BigInt here, never a number.
//
//   Floats. Python writes repr(float): always a dot or an exponent, exponential
//   below 1e-4 and from 1e16 up, exponent padded to two digits. JavaScript
//   writes 1 for 1.0, 10000000000000000 for 1e16, 1e-7 for 1e-07. Different at
//   every one of those.
//
// The model this file serialises, stated once so there is no guessing:
//
//   bigint  is a Python int.    1n   -> "1"
//   number  is a Python float.  1    -> "1.0"
//
// That is total and it is the only reading that survives round tripping, so
// canonicalAscii does not try to guess which one a plain 1 meant. Values that
// come out of parseCanonical below already carry the right one.
//
// None of this is proved by reading it. agreement_canonical_test.mjs takes the
// fixture's payload, which IS Python's canonical bytes for 5,221 cases and their
// reports, parses it by both routes, puts it back through here, and requires
// byte identity with what it read; and it checks every one of the 17,759 doubles
// in agreement_float_repr_v1.json, which Python wrote, not I.

const CP = (s) => Array.from(s, (c) => c.codePointAt(0));

// Python's sort_keys compares by code point. Do that, not the UTF-16 default.
export function cmpCodePoints(a, b) {
  if (a === b) return 0;
  const x = CP(a), y = CP(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) {
    if (x[i] !== y[i]) return x[i] < y[i] ? -1 : 1;
  }
  return x.length === y.length ? 0 : (x.length < y.length ? -1 : 1);
}

const SHORT = { 0x08: "\\b", 0x09: "\\t", 0x0a: "\\n", 0x0c: "\\f", 0x0d: "\\r" };

function hex4(n) {
  return "\\u" + n.toString(16).padStart(4, "0");
}

// Python's ESCAPE_ASCII: a backslash, a quote, or anything outside 0x20..0x7E.
// Iterate by UTF-16 unit, so an astral character comes through as its two
// surrogates and is written as a surrogate pair, exactly as Python writes it.
export function str(s) {
  let out = '"';
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c === 0x22) out += '\\"';
    else if (c === 0x5c) out += "\\\\";
    else if (SHORT[c] !== undefined) out += SHORT[c];
    else if (c < 0x20 || c > 0x7e) out += hex4(c);
    else out += s[i];
  }
  return out + '"';
}

// Python's repr for a finite double, digit for digit.
//
// CPython asks for the shortest digit string that reads back to the same double
// and then decides the shape from decpt, the position of the decimal point:
// exponential when decpt <= -4 or decpt > 16, fixed otherwise, and ".0" stuck on
// the end of a fixed form that would otherwise look like an integer. The
// exponent carries a sign and at least two digits.
//
// JavaScript's toExponential() with no argument is the same shortest digit
// string, so the digits are had for free and only the shape has to be rebuilt.
const EXP = /^(\d)(?:\.(\d+))?e([+-]\d+)$/;

function pyFinite(a) {           // a >= 0, finite
  const m = EXP.exec(a.toExponential());
  if (!m) throw new Error("toExponential の形が読めん: " + a.toExponential());
  const digits = m[1] + (m[2] || "");
  const decpt = Number(m[3]) + 1;
  if (decpt <= -4 || decpt > 16) {
    const mant = digits.length > 1 ? digits[0] + "." + digits.slice(1) : digits;
    const e = decpt - 1;
    return mant + "e" + (e < 0 ? "-" : "+") + String(Math.abs(e)).padStart(2, "0");
  }
  if (decpt <= 0) return "0." + "0".repeat(-decpt) + digits;
  if (decpt >= digits.length) return digits + "0".repeat(decpt - digits.length) + ".0";
  return digits.slice(0, decpt) + "." + digits.slice(decpt);
}

export function num(v) {
  if (typeof v === "bigint") return v.toString();       // Python int
  if (typeof v !== "number") throw new TypeError("数やない: " + typeof v);
  if (Number.isNaN(v)) return "NaN";                    // python json.dumps
  if (v === Infinity) return "Infinity";
  if (v === -Infinity) return "-Infinity";
  const neg = v < 0 || Object.is(v, -0);
  return (neg ? "-" : "") + pyFinite(neg ? -v : v);
}

// 記録層の canonical は ensure_ascii=False や。json.dumps(ensure_ascii=False) は
// 逃がす物が 3 つだけになる: 引用符、逆斜線、そして 0x20 未満の制御文字 (うち 5 つは
// 短い形)。0x7f も、日本語も、絵文字も、そのまま生で出る。
//
// 2 つ要る理由: 契約 (fixture の入れ物) は ASCII に逃がした形で、記録そのものは
// 逃がさん形や。片方だけ持っとったら canonical_sha256 が 576 件ずれる。
// (見つけ方: 採点板の初回で、ずれとる鍵の 2 番目に canonical_sha256 が出た)
export function strUtf8(s) {
  let out = '"';
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c === 0x22) out += '\\"';
    else if (c === 0x5c) out += "\\\\";
    else if (SHORT[c] !== undefined) out += SHORT[c];
    else if (c < 0x20) out += hex4(c);
    else out += s[i];
  }
  return out + '"';
}

function build(v, q) {
  if (v === null) return "null";
  const t = typeof v;
  if (t === "boolean") return v ? "true" : "false";
  if (t === "number" || t === "bigint") return num(v);
  if (t === "string") return q(v);
  if (Array.isArray(v)) return "[" + v.map((x) => build(x, q)).join(",") + "]";
  if (t === "object") {
    const keys = Object.keys(v).sort(cmpCodePoints);
    let out = "{", first = true;
    for (const k of keys) {
      if (!first) out += ",";
      first = false;
      out += q(k) + ":" + build(v[k], q);
    }
    return out + "}";
  }
  throw new TypeError("書けん型: " + t);
}

// 記録層の canonical: UTF-8、鍵は全段で並べ替え、区切りは , と : で空白無し、
// 非 ASCII は逃がさん。agreement_verify.py の canonical() と同じ物。
export function canonicalUtf8(v) {
  return build(v, strUtf8);
}

// 契約の入れ物の canonical: 上と同じで、非 ASCII を \uXXXX に逃がす形。
// json.dumps(sort_keys=True, separators=(",",":"), ensure_ascii=True) と同じ物。
// 中身は build を共有しとる。二本立てにしたら、いつか片方だけ直る。
export function canonicalAscii(v) {
  return build(v, str);
}

// ---------------------------------------------------------------------------
// Reading. The half nobody writes down and everybody gets wrong.
//
// JSON.parse gives every number as a double, so 1180591620717411303424 and
// 1.1805916207174113e+21 arrive as the same value and the record cannot be put
// back the way it came. Python does not lose that: json.loads gives an int of
// whatever size. So the source text of each number has to be looked at.
//
// And json.loads keeps the LAST of two identical keys and says nothing, which is
// why agreement_verify.py does not call it bare: it calls parse_strict, which
// refuses a duplicate key outright and reports duplicate_json_key. A record
// carrying "amount" twice would otherwise canonicalize to a number the person who
// read it never saw. This file has to refuse it in the same place, by the same
// name, or the two verifiers disagree about what is even readable.
//
// JSON.parse cannot help with that: by the time a reviver sees an object, the
// duplicate is already gone. So the reader the verifier uses is the scanner in
// this file, on every host, and there is no branch on what the host can do.
// parseNative stays for one job only: to be a second opinion on the scanner in
// the round trip test. It is not, and must not become, the reader.
//
//   parseStrict     what the verifier reads with. Refuses a duplicate key.
//   parseLoose      what bare json.loads does. Last key wins. For proving that.
//   parseNative     the host's JSON.parse. Cannot see duplicates. Test only.
//
// Errors carry .code so the caller can put the right refusal name in the report
// without reading English: duplicate_json_key, too_deep, bad_json.
// ---------------------------------------------------------------------------

// Depth. Measured 2026-09-10 against the real agreement_verify.py, not reasoned
// about: python's parse_strict took 993 levels and then took 994 as well, because
// RecursionError depends on how much stack is left at that moment, not on a
// number anybody chose. So there is no depth contract to copy. What IS a contract
// is verify's own MAX_DEPTH of 32: everything at 32 or deeper is refused too_deep
// by both sides, deterministically, and the deepest input in the 5,221 case
// fixture is 41. So this reader sets no ceiling of its own. It only catches the
// host running out of stack and reports it by the same name python's reader uses,
// so that an input neither reader can hold reads the same either way.

class CanonicalError extends SyntaxError {
  constructor(code, message) {
    super(message);
    this.name = "CanonicalError";
    this.code = code;
  }
}
export { CanonicalError };

const INTISH = /^-?\d+$/;

// Does this host hand the reviver the source text? Asked once, by asking.
export const HAS_JSON_SOURCE = (() => {
  try {
    let seen = false;
    JSON.parse("1", function (k, v, ctx) {
      seen = !!ctx && typeof ctx.source === "string";
      return v;
    });
    return seen;
  } catch {
    return false;
  }
})();

// Test only. Cannot see duplicate keys. Do not read records with this.
export function parseNative(text) {
  if (!HAS_JSON_SOURCE) {
    throw new CanonicalError("bad_json", "この JS には JSON.parse の source が無い");
  }
  return JSON.parse(text, function (key, value, ctx) {
    if (typeof value !== "number") return value;
    const src = ctx && ctx.source;
    if (typeof src !== "string") {
      // 数やのに source が無い。黙って double を返したら記録が変わる。止める。
      throw new CanonicalError("bad_json", "数の source が無い: key=" + JSON.stringify(key));
    }
    return INTISH.test(src) ? BigInt(src) : value;
  });
}

const isDigit = (c) => c >= 0x30 && c <= 0x39;
const HEX4 = /^[0-9a-fA-F]{4}$/;

function scan(text, opts) {
  const dupLastWins = !!(opts && opts.duplicates === "last");
  let i = 0;
  const n = text.length;

  const err = (code, m) => {
    throw new CanonicalError(code, m + " (" + i + " 文字目)");
  };

  const ws = () => {
    while (i < n) {
      const c = text.charCodeAt(i);
      if (c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d) i++;
      else break;
    }
  };

  const string = () => {
    i++;                                  // opening quote, already seen
    let out = "", start = i;
    for (;;) {
      if (i >= n) err("bad_json", "文字列が閉じとらん");
      const c = text.charCodeAt(i);
      if (c === 0x22) {
        out += text.slice(start, i);
        i++;
        return out;
      }
      if (c === 0x5c) {
        out += text.slice(start, i);
        i++;
        const e = text[i];
        i++;
        if (e === '"') out += '"';
        else if (e === "\\") out += "\\";
        else if (e === "/") out += "/";
        else if (e === "b") out += "\b";
        else if (e === "f") out += "\f";
        else if (e === "n") out += "\n";
        else if (e === "r") out += "\r";
        else if (e === "t") out += "\t";
        else if (e === "u") {
          const h = text.slice(i, i + 4);
          if (!HEX4.test(h)) err("bad_json", "\\u の後が 16 進 4 桁やない");
          // fromCharCode やから、対を組まん代理符号もそのまま残る。Python の
          // json.loads と同じ。ここで組み直したら記録が変わる。
          out += String.fromCharCode(parseInt(h, 16));
          i += 4;
        } else err("bad_json", "知らん逃がし方: \\" + e);
        start = i;
        continue;
      }
      if (c < 0x20) err("bad_json", "生の制御文字");
      i++;
    }
  };

  const number = () => {
    const s = i;
    if (text.charCodeAt(i) === 0x2d) i++;
    let c = text.charCodeAt(i);
    if (c === 0x30) i++;
    else if (c >= 0x31 && c <= 0x39) { i++; while (isDigit(text.charCodeAt(i))) i++; }
    else err("bad_json", "数が来てへん");
    let isInt = true;
    if (text.charCodeAt(i) === 0x2e) {
      isInt = false;
      i++;
      if (!isDigit(text.charCodeAt(i))) err("bad_json", "小数点の後に数字が無い");
      while (isDigit(text.charCodeAt(i))) i++;
    }
    c = text.charCodeAt(i);
    if (c === 0x65 || c === 0x45) {
      isInt = false;
      i++;
      c = text.charCodeAt(i);
      if (c === 0x2b || c === 0x2d) i++;
      if (!isDigit(text.charCodeAt(i))) err("bad_json", "指数に数字が無い");
      while (isDigit(text.charCodeAt(i))) i++;
    }
    const src = text.slice(s, i);
    return isInt ? BigInt(src) : Number(src);
  };

  const word = (w, v) => {
    if (text.slice(i, i + w.length) !== w) err("bad_json", "知らん語");
    i += w.length;
    return v;
  };

  const value = () => {
    ws();
    if (i >= n) err("bad_json", "値が来る所で終わっとる");
    const c = text.charCodeAt(i);
    if (c === 0x7b) {                     // {
      i++;
      const o = {};
      const seen = dupLastWins ? null : new Set();
      ws();
      if (text.charCodeAt(i) === 0x7d) { i++; return o; }
      for (;;) {
        ws();
        if (text.charCodeAt(i) !== 0x22) err("bad_json", "鍵は文字列やないとあかん");
        const k = string();
        if (seen) {
          // agreement_verify.py の parse_strict と同じ所で、同じ名前で断る。
          if (seen.has(k)) err("duplicate_json_key", "duplicate key in JSON object: " + k);
          seen.add(k);
        }
        ws();
        if (text.charCodeAt(i) !== 0x3a) err("bad_json", "鍵の後に : が無い");
        i++;
        // 緩い側は後勝ち。python の json.loads がそうやから、そう写す。
        o[k] = value();
        ws();
        const d = text.charCodeAt(i);
        if (d === 0x2c) { i++; continue; }
        if (d === 0x7d) { i++; return o; }
        err("bad_json", "object に , か } が無い");
      }
    }
    if (c === 0x5b) {                     // [
      i++;
      const a = [];
      ws();
      if (text.charCodeAt(i) === 0x5d) { i++; return a; }
      for (;;) {
        a.push(value());
        ws();
        const d = text.charCodeAt(i);
        if (d === 0x2c) { i++; continue; }
        if (d === 0x5d) { i++; return a; }
        err("bad_json", "array に , か ] が無い");
      }
    }
    if (c === 0x22) return string();
    if (c === 0x74) return word("true", true);
    if (c === 0x66) return word("false", false);
    if (c === 0x6e) return word("null", null);
    // NaN と Infinity。json.loads は既定でこれを通す。通したなる所やが、通す。
    // 断ったら報告書がずれるからや。python は読んだ上で verify が unsafe_number と
    // 書いて断る。ここで bad_json と書いてしもたら、同じ入力に二つの言語が別の
    // 名前を付ける。どこで断るかやのうて、何と呼ぶかが揃うとらんとあかん。
    // (見つけ方: 断る作りで先に書いて、python の parse_strict と突き合わせたら
    //  この 3 語だけ食い違うた。2026-09-10)
    if (c === 0x4e) return word("NaN", NaN);
    if (c === 0x49) return word("Infinity", Infinity);
    if (c === 0x2d && text.charCodeAt(i + 1) === 0x49) return word("-Infinity", -Infinity);
    if (c === 0x2d || isDigit(c)) return number();
    err("bad_json", "値の頭が読めん: " + JSON.stringify(text[i]));
  };

  const v = value();
  ws();
  if (i !== n) err("bad_json", "末尾に余りがある");
  return v;
}

export function parseScan(text, opts) {
  try {
    return scan(text, opts);
  } catch (e) {
    if (e instanceof RangeError) {
      // 宿主の stack が尽きた。python の読み手が RecursionError で諦めた時に
      // agreement_verify.py が書くのと同じ名前、同じ文で返す。
      throw new CanonicalError("too_deep", "the JSON is nested past what a reader can parse");
    }
    throw e;
  }
}

// What the verifier reads records with. Refuses a duplicate key by name.
export function parseStrict(text) {
  return parseScan(text);
}

// What bare json.loads does: the last of two identical keys wins, silently.
// Here so that the agreement with python can be shown rather than assumed.
export function parseLoose(text) {
  return parseScan(text, { duplicates: "last" });
}

export const parseCanonical = parseStrict;


// ============================== recovery-v0/recovery_schema.mjs ==============================
//
// TSUGI (継、旧称 Proof-of-Recovery) の記録 5 種 (設計書 5 節)。
//   drift → proposal → authorization → execution → verify
// 全部 append-only。prev に前の記録の record_sha256 を持つ。drift だけ prev が null (区間の頭)。
// establishes / does_not_establish は conduct-v1.1 と同じ規律: 無い・空は拒否 (disclaimer_missing)。
//
// v0 の約束 (2026-09-20): 記録に JSON の数は入れん。数は文字列で持つ ("43")。
// 理由は agreement_canonical.mjs の頭に書いてある int / float の継ぎ目や。v0 はそこを踏まん。
// 数を入れる版 (v1) は RFC 8785 か parseStrict を採る。それまでは文字列。

export const SCHEMAS = {
  drift: "nenrin-drift-record-v1",
  proposal: "nenrin-repair-proposal-v1",
  authorization: "nenrin-authorization-v1",
  execution: "nenrin-repair-execution-v1",
  verify: "nenrin-verify-record-v1",
  // v2 (設計書 14 節): 籤で引いた外部証人が返す観測。連鎖には並ばん。verify.external[].record に埋め込まれる。
  observation: "nenrin-witness-observation-v1",
};
export const ORDER = [SCHEMAS.drift, SCHEMAS.proposal, SCHEMAS.authorization, SCHEMAS.execution, SCHEMAS.verify];
export const EMBEDDED = [SCHEMAS.observation];

// v1 のカタログ。閉じた一覧 (設計書 6 節)。ここに無いプリミティブは提案も実行も拒否。追加は ADR。
export const PRIMITIVES = {
  quarantine_endpoint:            { reversible: true,  approval: "auto"  },
  redeploy_pinned:                { reversible: true,  approval: "human" },
  resign_agent_card:              { reversible: true,  approval: "human" },
  revert_to_last_witnessed_good:  { reversible: true,  approval: "human" },
  rotate_credential:              { reversible: false, approval: "human" },
};

const HEX64 = /^[0-9a-f]{64}$/;
const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;

const isStr = (v) => typeof v === "string" && v.length > 0;
const isStrArr = (v) => Array.isArray(v) && v.length > 0 && v.every(isStr);
const isObj = (v) => !!v && typeof v === "object" && !Array.isArray(v);
const isHex = (v) => isStr(v) && HEX64.test(v);
const isDigits = (v) => isStr(v) && /^[0-9]+$/.test(v);
const isHttps = (v) => isStr(v) && /^https:\/\/[^\s/]+/.test(v);

// 数が紛れ込んどらんか (v0 の約束)。深さ優先で見る。
export function hasNumber(v) {
  if (typeof v === "number" || typeof v === "bigint") return true;
  if (Array.isArray(v)) return v.some(hasNumber);
  if (isObj(v)) return Object.values(v).some(hasNumber);
  return false;
}

function checkCommon(r, refuse) {
  if (!isObj(r)) { refuse("not_object", "record is not a JSON object"); return; }
  if (!ORDER.includes(r.schema) && !EMBEDDED.includes(r.schema)) refuse("bad_schema", "schema must be one of " + ORDER.concat(EMBEDDED).join(", "));
  if (!isStr(r.recorded_at) || !ISO.test(r.recorded_at)) refuse("bad_recorded_at", "recorded_at must be ISO-8601 UTC ending in Z");
  if (!isObj(r.witness) || !isStr(r.witness.name) || !isStr(r.witness.vantage)) refuse("bad_witness", "witness.name and witness.vantage are required");
  if (!isStrArr(r.establishes)) refuse("disclaimer_missing", "establishes must be a non-empty array of strings");
  if (!isStrArr(r.does_not_establish)) refuse("disclaimer_missing", "does_not_establish must be a non-empty array of strings");
  if (!(r.prev === null || isHex(r.prev))) refuse("bad_prev", "prev must be null or 64 hex");
  if (r.record_sha256 !== undefined && !isHex(r.record_sha256)) refuse("bad_record_sha256", "record_sha256, when present, must be 64 hex");
  if (hasNumber(r)) refuse("number_in_record", "v0 records carry no JSON numbers; write counts as strings");
}

const CHECK = {
  [SCHEMAS.drift](r, refuse) {
    if (!isStr(r.endpoint)) refuse("bad_endpoint", "endpoint is required");
    if (!isStr(r.surface)) refuse("bad_surface", "surface is required (what was measured)");
    if (typeof r.drift !== "boolean") refuse("bad_drift", "drift must be a boolean");
    if (!isObj(r.observed)) refuse("bad_observed", "observed must be an object");
    if (!isObj(r.expected)) refuse("bad_expected", "expected must be an object");
    if (r.drift === true && !isStr(r.kind)) refuse("bad_kind", "kind is required when drift is true");
    if (r.prev !== null) refuse("bad_prev", "a drift record starts a segment: prev must be null");
    if (r.source !== undefined && !isObj(r.source)) refuse("bad_source", "source, when present, is an object naming the external witness");
  },
  [SCHEMAS.proposal](r, refuse) {
    if (!Array.isArray(r.drift_sha256) || r.drift_sha256.length === 0 || !r.drift_sha256.every(isHex)) refuse("bad_drift_sha256", "drift_sha256 must be a non-empty array of 64 hex");
    if (!isStr(r.primitive) || !(r.primitive in PRIMITIVES)) refuse("primitive_not_in_catalog", "primitive must be one of " + Object.keys(PRIMITIVES).join(", "));
    if (!isStr(r.diagnosis)) refuse("bad_diagnosis", "diagnosis is required");
    if (!isObj(r.expected_after)) refuse("bad_expected_after", "expected_after must be an object: surface -> expected state");
    if (!isStr(r.rollback)) refuse("bad_rollback", "rollback is required");
    if (!isHex(r.prev)) refuse("bad_prev", "proposal must link to the last drift record");
    if (r.rejected !== undefined && !(Array.isArray(r.rejected) && r.rejected.every((x) => isObj(x) && isStr(x.primitive) && isStr(x.why)))) refuse("bad_rejected", "rejected entries need primitive and why");
  },
  [SCHEMAS.authorization](r, refuse) {
    if (!isHex(r.proposal_sha256)) refuse("bad_proposal_sha256", "proposal_sha256 must be 64 hex");
    if (!["approved", "refused"].includes(r.decision)) refuse("bad_decision", "decision must be approved or refused");
    if (!isStr(r.by)) refuse("bad_by", "by is required (who decided)");
    if (!isStr(r.expires_at) || !ISO.test(r.expires_at)) refuse("bad_expires_at", "expires_at must be ISO-8601 UTC");
    if (!isHex(r.prev)) refuse("bad_prev", "authorization must link to the proposal");
    else if (r.prev !== r.proposal_sha256) refuse("prev_mismatch", "authorization.prev must equal proposal_sha256");
  },
  [SCHEMAS.execution](r, refuse) {
    if (!isHex(r.authorization_sha256)) refuse("bad_authorization_sha256", "authorization_sha256 must be 64 hex");
    if (!isStr(r.primitive) || !(r.primitive in PRIMITIVES)) refuse("primitive_not_in_catalog", "primitive must be in the catalog");
    if (!isObj(r.before)) refuse("bad_before", "before must be an object (state before)");
    if (!isObj(r.after)) refuse("bad_after", "after must be an object (state after)");
    if (!["ok", "failed", "rolled_back"].includes(r.outcome)) refuse("bad_outcome", "outcome must be ok, failed or rolled_back");
    if (!isStrArr(r.steps)) refuse("bad_steps", "steps must be a non-empty array of strings");
    if (!isHex(r.prev)) refuse("bad_prev", "execution must link to the authorization");
    else if (r.prev !== r.authorization_sha256) refuse("prev_mismatch", "execution.prev must equal authorization_sha256");
  },
  [SCHEMAS.verify](r, refuse) {
    if (!isHex(r.execution_sha256)) refuse("bad_execution_sha256", "execution_sha256 must be 64 hex");
    if (!isObj(r.observed)) refuse("bad_observed", "observed must be an object");
    if (!isObj(r.expected_after)) refuse("bad_expected_after", "expected_after must be an object");
    if (typeof r.recovered !== "boolean") refuse("bad_recovered", "recovered must be a boolean");
    if (r.external !== undefined && !Array.isArray(r.external)) refuse("bad_external", "external, when present, is an array of external witness results");
    else if (Array.isArray(r.external)) {
      // v0 の自由形 (witness / status / result) はそのまま許す。record を持つ項 (v2) だけ形を見る。
      for (const e of r.external) {
        if (!isObj(e)) { refuse("bad_external", "external entries must be objects"); continue; }
        if (e.record !== undefined) {
          if (!isObj(e.record)) refuse("bad_external", "external[].record, when present, is the witness's signed observation record");
          if (!isStr(e.signed_domain)) refuse("bad_external", "external[].signed_domain is required beside a record");
        }
        if (e.answered !== undefined && typeof e.answered !== "boolean") refuse("bad_external", "external[].answered, when present, is a boolean");
      }
    }
    // v2 籤 (設計書 14.3): 誰を呼んだかを再計算できる形で持つ。無くてもよい (v0 互換)。在るなら形は固い。
    if (r.draw !== undefined) {
      const d = r.draw;
      if (!isObj(d)) refuse("bad_draw", "draw must be an object");
      else {
        if (!isObj(d.beacon) || !isStr(d.beacon.kind) || !isDigits(d.beacon.height) || !isHex(d.beacon.hash)) refuse("bad_draw", "draw.beacon needs kind, height (digits as a string) and hash (64 hex)");
        if (!isHex(d.pool_sha256)) refuse("bad_draw", "draw.pool_sha256 must be 64 hex");
        if (!isDigits(d.pool_size)) refuse("bad_draw", "draw.pool_size must be digits as a string");
        if (!isDigits(d.k)) refuse("bad_draw", "draw.k must be digits as a string");
        if (!isHex(d.subject_sha256)) refuse("bad_draw", "draw.subject_sha256 must be 64 hex (the record the draw serves)");
        if (!isHex(d.request_sha256)) refuse("bad_draw", "draw.request_sha256 must be 64 hex (the request every drawn witness received)");
        if (!Array.isArray(d.drawn) || !d.drawn.every(isStr)) refuse("bad_draw", "draw.drawn must be an array of signed_domain strings (may be empty when the pool is empty)");
        // v2.2 commit-then-reveal: 在るなら形は固い。無くてもよい (方針で要求するのは検証器の witnessQuorum.requireCommitment)
        if (d.commitment !== undefined) {
          const c = d.commitment;
          if (!isObj(c)) refuse("bad_draw", "draw.commitment must be an object");
          else {
            if (!isHex(c.subject_sha256)) refuse("bad_draw", "draw.commitment.subject_sha256 must be 64 hex");
            if (!isDigits(c.ledger_entry)) refuse("bad_draw", "draw.commitment.ledger_entry must be digits as a string");
            if (!isHttps(c.ledger_url)) refuse("bad_draw", "draw.commitment.ledger_url must be https");
            if (!isHex(c.claim_sha256)) refuse("bad_draw", "draw.commitment.claim_sha256 must be 64 hex");
            if (!isObj(c.anchor) || !isStr(c.anchor.kind) || !isDigits(c.anchor.height) || !isHex(c.anchor.hash)) refuse("bad_draw", "draw.commitment.anchor needs kind, height (digits as a string) and hash (64 hex)");
          }
        }
      }
    }
    if (!isHex(r.prev)) refuse("bad_prev", "verify must link to the execution");
    else if (r.prev !== r.execution_sha256) refuse("prev_mismatch", "verify.prev must equal execution_sha256");
  },
  // v2: 外部証人の観測。証人が自分の domain 鍵で署名して返す 1 記録。連鎖の外、verify.external[].record の中に居る。
  // 「指示」の欄は無い。observed の hash が比べられるだけ。証人が何を書いても Shield は動かん (設計書 14.1)。
  [SCHEMAS.observation](r, refuse) {
    if (!isStr(r.endpoint)) refuse("bad_endpoint", "endpoint is required (the origin that was measured)");
    if (!isObj(r.observed) || Object.keys(r.observed).length === 0 || !Object.values(r.observed).every(isObj)) refuse("bad_observed", "observed must be an object: surface -> observed state object");
    if (!isHex(r.request_sha256)) refuse("bad_request_sha256", "request_sha256 must be 64 hex (canonical sha256 of the request the witness answered)");
    if (!isObj(r.source) || r.source.kind !== "external_witness" || !isStr(r.source.signed_domain) || !isHttps(r.source.key_url)) refuse("bad_source", "source must be { kind: external_witness, signed_domain, key_url (https) }");
    else if (r.source.key_url && r.source.signed_domain) {
      let host = ""; try { host = new URL(r.source.key_url).host; } catch {}
      if (host.toLowerCase() !== r.source.signed_domain.toLowerCase()) refuse("bad_source", "source.signed_domain must be the host of source.key_url (conduct-v1.1 11.4)");
    }
    if (r.prev !== null) refuse("bad_prev", "an observation stands alone: prev must be null");
  },
};

// 1 記録の型検査。断りの一覧を返す (空 = 型は通った)。同じ (code, why) は一度だけ。
export function validate(record) {
  const refusals = [];
  const seen = new Set();
  const refuse = (code, why) => { const k = code + "|" + why; if (seen.has(k)) return; seen.add(k); refusals.push({ code, why }); };
  checkCommon(record, refuse);
  if (isObj(record) && CHECK[record.schema]) CHECK[record.schema](record, refuse);
  return refusals;
}


// ============================== recovery-v0/witness_draw.mjs ==============================
//
// 「ランダムに選んだ」は自分で言うても誰も確かめられん (設計書 14.3)。せやから:
//   seed = sha256(beacon_hash | pool_sha256 | subject_sha256)
//     beacon_hash   自分の外の乱数。Bitcoin の、対象記録より後に最初に採掘されたブロックの hash。
//     pool_sha256   池 (witness_pool.json) の正規化 canonical の sha256。池を入れ替えたら変わる。
//     subject_sha256 籤が仕える記録の record_sha256 (再検証なら execution)。事故ごとに違う = 使い回せん。
//   池を public_key_ed25519_b64 の code point 順に並べ、seed から決定的な部分 Fisher-Yates で k 人引く。
// 誰でも同じ 3 入力から同じ k 人を出せる。出せんかったら Shield が選り好みした (verifier: draw_mismatch)。
//
// 数は文字列 (v0 の約束)。sha256 は WebCrypto (Worker と node で同じ)。python の双子は recovery_verify.py の draw()。
// 自分の host は引く前に外す (self_witness、conduct-v1.1 11.4)。

export const POOL_SCHEMA = "nenrin-witness-pool-v1";
export const DRAW_VERSION = "0.1.0";
const enc = new TextEncoder();

async function drawSha256(s) {   // recovery_verify.sha256Hex と同じ物。export せん (1 file SDK で名前がぶつかる)
  const d = await globalThis.crypto.subtle.digest("SHA-256", typeof s === "string" ? enc.encode(s) : s);
  return [...new Uint8Array(d)].map((x) => x.toString(16).padStart(2, "0")).join("");
}

const hashedEntry = (e) => ({ signed_domain: e.signed_domain, key_url: e.key_url, public_key_ed25519_b64: e.public_key_ed25519_b64 });

// 池の正規化。file の順は信用せん: 鍵の code point 順に並べる。鍵も domain も重複は拒否 (一 domain 一票、11.4)。
export function normalizePool(pool) {
  const entries = Array.isArray(pool) ? pool : (pool && Array.isArray(pool.entries) ? pool.entries : null);
  if (!entries) throw new Error("pool must be an array of entries or { entries: [...] }");
  const out = entries.map((e) => {
    if (!e || typeof e !== "object" || Array.isArray(e)) throw new Error("pool entry is not an object");
    for (const k of ["signed_domain", "key_url", "public_key_ed25519_b64"]) if (typeof e[k] !== "string" || !e[k]) throw new Error("pool entry lacks " + k);
    let host = ""; try { host = new URL(e.key_url).host; } catch { throw new Error("pool entry key_url is not a URL: " + e.key_url); }
    if (host.toLowerCase() !== e.signed_domain.toLowerCase()) throw new Error("pool entry signed_domain " + e.signed_domain + " is not the host of its key_url (11.4)");
    return { ...hashedEntry(e), ...(typeof e.a2a_url === "string" ? { a2a_url: e.a2a_url } : {}) };
  });
  out.sort((a, b) => (a.public_key_ed25519_b64 < b.public_key_ed25519_b64 ? -1 : a.public_key_ed25519_b64 > b.public_key_ed25519_b64 ? 1 : 0));
  const keys = new Set(), domains = new Set();
  for (const e of out) {
    if (keys.has(e.public_key_ed25519_b64)) throw new Error("pool has a duplicate key " + e.public_key_ed25519_b64);
    if (domains.has(e.signed_domain.toLowerCase())) throw new Error("pool has a duplicate domain " + e.signed_domain);
    keys.add(e.public_key_ed25519_b64); domains.add(e.signed_domain.toLowerCase());
  }
  return out;
}

// 池の hash。a2a_url は運搬先で、身元やない。hash に入れん。
export function poolCanonical(pool) { return canonicalUtf8({ schema: POOL_SCHEMA, entries: normalizePool(pool).map(hashedEntry) }); }
export async function poolSha256(pool) { return drawSha256(poolCanonical(pool)); }

// 籤。返す物: pool_sha256, pool_size, k (実際に引けた数), seed_sha256, drawn (signed_domain の列), entries (引いた項)。
export async function draw({ pool, beaconHash, subjectSha256, k, excludeHost }) {
  if (!HEX64.test(String(beaconHash || ""))) throw new Error("beaconHash must be 64 hex (a Bitcoin block hash)");
  if (!HEX64.test(String(subjectSha256 || ""))) throw new Error("subjectSha256 must be 64 hex (the record_sha256 the draw serves)");
  const want = Number(k);
  if (!Number.isInteger(want) || want < 0) throw new Error("k must be a non-negative integer");
  const all = normalizePool(pool);
  const pool_sha256 = await drawSha256(canonicalUtf8({ schema: POOL_SCHEMA, entries: all.map(hashedEntry) }));
  const ex = excludeHost ? String(excludeHost).toLowerCase() : null;
  const eligible = all.filter((e) => !ex || e.signed_domain.toLowerCase() !== ex);
  const n = eligible.length;
  const kk = Math.min(want, n);
  const seed = await drawSha256(beaconHash + "|" + pool_sha256 + "|" + subjectSha256);
  const arr = eligible.slice();
  for (let i = 0; i < kk; i++) {
    const r = await drawSha256(seed + "|" + String(i));
    const j = i + Number(BigInt("0x" + r.slice(0, 16)) % BigInt(n - i));
    const tmp = arr[i]; arr[i] = arr[j]; arr[j] = tmp;
  }
  const chosen = arr.slice(0, kk);
  return { pool_sha256, pool_size: String(all.length), eligible: String(n), k: String(kk), k_requested: String(want), seed_sha256: seed, drawn: chosen.map((e) => e.signed_domain), entries: chosen };
}

// verify 記録に焼く draw 欄 (recovery_schema の verify.draw)。beacon: { kind, height, hash }。
// commitment (v2.2、任意やが方針で必須にできる): subject を先に台帳に錨打ちした証拠。
//   { subject_sha256, ledger_entry, ledger_url, claim_sha256, anchor: { kind, height, hash } }
//   beacon は anchor の次のブロック (height = anchor.height + 1) でなければならん。検証器が見る。
export function drawField(d, beacon, subjectSha256, requestSha256, commitment) {
  return {
    beacon: { kind: String(beacon.kind), height: String(beacon.height), hash: String(beacon.hash) },
    pool_sha256: d.pool_sha256, pool_size: d.pool_size, k: d.k,
    subject_sha256: subjectSha256, request_sha256: requestSha256, drawn: d.drawn.slice(),
    ...(commitment ? { commitment: {
      subject_sha256: String(commitment.subject_sha256), ledger_entry: String(commitment.ledger_entry), ledger_url: String(commitment.ledger_url), claim_sha256: String(commitment.claim_sha256),
      anchor: { kind: String(commitment.anchor.kind), height: String(commitment.anchor.height), hash: String(commitment.anchor.hash) },
    } } : {}),
  };
}

// ---- v2.2 commit-then-reveal (設計書 14.6 の「籤の穴」の塞ぎ) ----
// 研磨 (grinding): subject は運営者が書く記録の hash やから、beacon が出た後に文面を弄って seal し直せば種が変わる。
// 塞ぎ方: subject を先に公開台帳 (JIDEC) に append し、OTS で Bitcoin のブロック (anchor) に固定する。
// beacon は anchor の次のブロック。anchor が出た時点で subject は動かせん、beacon はまだ誰も知らん。
// 読む側は: (1) 台帳の entry を取り、claim_sha256 が commitmentClaimText(subject) の sha256 と同じか、
//          (2) その entry の .ots を自分で検証して anchor のブロック高さを得、
//          (3) 自分の chain 源から anchor+1 のブロック hash を取り、記録の beacon と同じか、を見る。
export const COMMITMENT_SCHEMA = "tsugi-draw-commitment-v1";
export function commitmentClaimText(subjectSha256) {
  if (!HEX64.test(String(subjectSha256 || ""))) throw new Error("subjectSha256 must be 64 hex");
  // 台帳の record_canonical そのもの。1 バイトも自由度を持たせん (持たせたら研磨の余地になる)。
  return "# " + COMMITMENT_SCHEMA + "\n\nsubject_sha256: " + subjectSha256 + "\n\nThis entry commits the record named by subject_sha256 (a TSUGI execution record) to the ledger before any re-verification witness is drawn. The draw's beacon must be the Bitcoin block after the block this entry is anchored to. Establishes: that subject_sha256 existed no later than the anchor block. Does not establish: anything about the record's content.\n";
}
export async function commitmentSeed(subjectSha256) {
  const record_canonical = commitmentClaimText(subjectSha256);
  return { claim_sha256: await drawSha256(record_canonical), record_canonical, work: "TSUGI draw commitment: fixes the subject of a witness draw on Bitcoin before the beacon block exists, so the operator cannot re-grind the draw by editing the record." };
}

// 高さ h のブロック (mempool.space、予備 blockstream.info)。commit-then-reveal の beacon = anchor.height + 1 を取る。
export async function bitcoinBlockAt(height, { fetchImpl = globalThis.fetch, bases = ["https://mempool.space/api", "https://blockstream.info/api"] } = {}) {
  const h = Number(height);
  if (!Number.isInteger(h) || h < 0) throw new Error("height must be a non-negative integer");
  let lastErr = null;
  for (const base of bases) {
    try {
      const get = async (p) => { const r = await fetchImpl(base + p, { signal: AbortSignal.timeout(15000) }); if (!r.ok) throw new Error(base + p + " http " + r.status); return r; };
      const hash = (await (await get("/block-height/" + h)).text()).trim();
      if (!HEX64.test(hash)) throw new Error("no block at height " + h + " yet");
      const b = await (await get("/block/" + hash)).json();
      return { kind: "bitcoin_block", height: String(h), hash, timestamp: String(b.timestamp), source: base };
    } catch (e) { lastErr = e; }
  }
  throw lastErr || new Error("no beacon source answered");
}

// Bitcoin の beacon: 与えた時刻 (ISO) 以後に最初に採掘されたブロック。mempool.space の公開 API、予備に blockstream.info。
// 先端から後ろへ歩く (上限 blocks)。JIDEC が既に Bitcoin にアンカーしとるので、新しい信用先やない。
export async function bitcoinBeaconAfter(isoTime, { fetchImpl = globalThis.fetch, bases = ["https://mempool.space/api", "https://blockstream.info/api"], maxWalk = 300 } = {}) {
  const t = Math.floor(new Date(isoTime).getTime() / 1000);
  if (!Number.isFinite(t)) throw new Error("isoTime is not a date: " + isoTime);
  let lastErr = null;
  for (const base of bases) {
    try {
      const get = async (p) => { const r = await fetchImpl(base + p, { signal: AbortSignal.timeout(15000) }); if (!r.ok) throw new Error(base + p + " http " + r.status); return r; };
      const tip = Number(await (await get("/blocks/tip/height")).text());
      let h = tip, candidate = null;
      for (let steps = 0; steps < maxWalk && h >= 0; steps++, h--) {
        const hash = (await (await get("/block-height/" + h)).text()).trim();
        const b = await (await get("/block/" + hash)).json();
        const ts = Number(b.timestamp);
        if (ts >= t) { candidate = { kind: "bitcoin_block", height: String(h), hash, timestamp: String(ts), source: base }; continue; }
        break;
      }
      if (!candidate) throw new Error("no block at or after " + isoTime + " within " + maxWalk + " blocks of the tip");
      return candidate;
    } catch (e) { lastErr = e; }
  }
  throw lastErr || new Error("no beacon source answered");
}



// ============================== recovery-v0/recovery_verify.mjs ==============================
//
// 何を検証するか:
//   1 記録:  型 (recovery_schema) / record_sha256 の再計算 / (在れば) Ed25519 署名
//   連鎖:    drift+ → proposal → authorization → execution → verify の順、prev の鎖、参照 hash の実値、
//            許可されとらん実行の拒否、提案と実行のプリミティブ一致、提案と再検証の expected_after 一致
//   v2 籤:   verify.draw が池と beacon から再計算できるか、verify.external[].record (外部証人の観測) の署名と
//            身元、引かれた証人か、定足数 (witnessQuorum) に届いとるか
//
// canonical bytes は agreement_canonical.canonicalUtf8 をそのまま使う (witness intake と同じ、ensure_ascii=False)。
// 二本立てにせん。hash は record_sha256 と署名 2 欄を除いた canonical bytes に対して取る。
// 非同期な理由は agreement_verify.mjs と同じ: sha256 も Ed25519 も WebCrypto。Worker に同期の口が無い。

export const VERIFIER_VERSION = "0.3.0"; // v2: random witness draw + quorum (v1: signed operator authorization)

export async function sha256Hex(bytes) {
  const b = typeof bytes === "string" ? enc.encode(bytes) : bytes;
  const d = await globalThis.crypto.subtle.digest("SHA-256", b);
  return [...new Uint8Array(d)].map((x) => x.toString(16).padStart(2, "0")).join("");
}

// hash と署名の対象: 自分の hash と署名 2 欄を除いた本体。
export function hashedBody(record) {
  const { record_sha256, signature_ed25519_b64, public_key_ed25519_b64, ...rest } = record;
  return rest;
}
export function canonicalText(record) { return canonicalUtf8(hashedBody(record)); }
export function canonicalBytes(record) { return enc.encode(canonicalText(record)); }
export async function recordSha256(record) { return sha256Hex(canonicalBytes(record)); }

// 本体に record_sha256 を焼く。既にある hash と署名は捨てて計算し直す (古い hash を引き継がん)。
export async function seal(record) {
  const r = { ...hashedBody(record) };
  r.record_sha256 = await recordSha256(r);
  return r;
}

const b64ToBytes = (s) => Uint8Array.from(Buffer.from(s, "base64"));
const bytesToB64 = (b) => Buffer.from(b).toString("base64");

// Ed25519 (witness intake と同じ欄名): canonical bytes への署名。
export async function verifySignature(record) {
  const sig = record.signature_ed25519_b64, pub = record.public_key_ed25519_b64;
  if (!sig || !pub) return { ok: false, why: "signature_ed25519_b64 and public_key_ed25519_b64 must both be present" };
  try {
    const key = await globalThis.crypto.subtle.importKey("raw", b64ToBytes(pub), { name: "Ed25519" }, false, ["verify"]);
    const ok = await globalThis.crypto.subtle.verify({ name: "Ed25519" }, key, b64ToBytes(sig), canonicalBytes(record));
    return ok ? { ok: true } : { ok: false, why: "Ed25519 signature does not verify over the canonical bytes" };
  } catch (e) {
    return { ok: false, why: "signature check failed: " + (e && e.message || e) };
  }
}

// 署名して返す。privateKey は WebCrypto の CryptoKey (Ed25519, sign)、publicKeyRaw は 32 バイト。
export async function sign(record, privateKey, publicKeyRaw) {
  const r = await seal(record);
  const sig = await globalThis.crypto.subtle.sign({ name: "Ed25519" }, privateKey, canonicalBytes(r));
  return { ...r, signature_ed25519_b64: bytesToB64(sig), public_key_ed25519_b64: bytesToB64(publicKeyRaw) };
}

// 1 記録の検証。
export async function verifyRecord(record) {
  const refusals = validate(record);
  if (refusals.length) return { ok: false, refusals };
  const h = await recordSha256(record);
  if (record.record_sha256 !== undefined && record.record_sha256 !== h) {
    return { ok: false, refusals: [{ code: "hash_mismatch", why: "record_sha256 does not recompute: carried " + record.record_sha256 + ", computed " + h }] };
  }
  if (record.signature_ed25519_b64 !== undefined || record.public_key_ed25519_b64 !== undefined) {
    const s = await verifySignature(record);
    if (!s.ok) return { ok: false, refusals: [{ code: "bad_signature", why: s.why }] };
  }
  return { ok: true, refusals: [], record_sha256: h };
}

// expected の全部が observed に (同じ値で) 在るか。observed が余分に持つ分は構わん (証人は tool や status も書く)。
export function subsetMatches(expected, observed) {
  const isObj = (v) => !!v && typeof v === "object" && !Array.isArray(v);
  if (isObj(expected) && isObj(observed)) return Object.keys(expected).every((k) => k in observed && subsetMatches(expected[k], observed[k]));
  return canonicalUtf8(expected) === canonicalUtf8(observed);
}
const hostOf = (u) => { try { return new URL(u).host.toLowerCase(); } catch { return ""; } };

// v2 籤の検証 (設計書 14.3〜14.5)。verify 記録 1 つを見る。
//   ownHost: 自分の host (drawn に居たら self_witness)。endpoint: 測られた origin。executionSha256: 籤が仕える記録。
//   quorum: { q, pool, beaconHash } の任意の組。pool を渡すと籤を再計算 (pool_mismatch / draw_mismatch)、
//   beaconHash を渡すと記録の beacon と突き合わせ (beacon_mismatch)、q を渡すと recovered:true に q 人の一致を要求 (witness_quorum_short)。
// 数えるのは: 署名が通り、引かれた domain で、池の鍵で署名され、同じ依頼に答え、expected_after を observed が含む観測。一 domain 一票。
export async function verifyWitnesses(verify, { ownHost, endpoint, executionSha256, executionAt, quorum } = {}) {
  const refusals = [];
  const refuse = (code, why) => refusals.push({ code, why });
  const q = quorum && quorum.q !== undefined && quorum.q !== null ? Number(quorum.q) : null;
  const pool = quorum && quorum.pool ? quorum.pool : null;
  const beaconHash = quorum && quorum.beaconHash ? String(quorum.beaconHash).toLowerCase() : null;
  const kExpected = quorum && quorum.k !== undefined && quorum.k !== null ? String(quorum.k) : null;
  const requireCommitment = !!(quorum && quorum.requireCommitment);
  const commitmentAnchor = quorum && quorum.commitmentAnchor ? quorum.commitmentAnchor : null;   // 読む側が台帳の entry の .ots から自分で得た { height, hash }
  const d = verify.draw;
  const drawn = d && Array.isArray(d.drawn) ? d.drawn : [];
  const own = ownHost ? String(ownHost).toLowerCase() : "";
  if (d) {
    if (executionSha256 && d.subject_sha256 !== executionSha256) refuse("draw_subject_mismatch", "draw.subject_sha256 " + d.subject_sha256 + " is not the execution record_sha256 " + executionSha256);
    if (own && drawn.some((x) => String(x).toLowerCase() === own)) refuse("self_witness", "the draw lists the endpoint's own host " + ownHost + " as a witness (11.4)");
    if (beaconHash && String(d.beacon.hash).toLowerCase() !== beaconHash) refuse("beacon_mismatch", "draw.beacon.hash " + d.beacon.hash + " is not the beacon the verifier fetched " + beaconHash);
    if (kExpected && d.k !== kExpected && d.pool_size !== "0" && Number(d.k) < Number(kExpected)) refuse("draw_mismatch", "draw.k " + d.k + " is below the policy k " + kExpected + " (the operator may not shorten the draw)");
    // v2.2 commit-then-reveal: subject が beacon より前に錨打ちされとるか
    const c = d.commitment;
    if (requireCommitment && !c) refuse("draw_uncommitted", "policy requires the draw's subject to be anchored on the ledger before the beacon block; draw.commitment is absent (the operator could have re-ground the draw)");
    if (c) {
      if (c.subject_sha256 !== d.subject_sha256) refuse("draw_subject_mismatch", "draw.commitment.subject_sha256 is not draw.subject_sha256");
      const claim = await sha256Hex(commitmentClaimText(c.subject_sha256));
      if (c.claim_sha256 !== claim) refuse("commitment_claim_mismatch", "draw.commitment.claim_sha256 " + c.claim_sha256 + " is not sha256(commitmentClaimText(subject)) " + claim + ": the ledger entry named does not commit this subject");
      if (String(Number(c.anchor.height) + 1) !== String(d.beacon.height)) refuse("beacon_not_next_block", "beacon.height " + d.beacon.height + " is not anchor.height + 1 (" + c.anchor.height + " + 1): the beacon must be the block after the one the subject is anchored to");
      if (commitmentAnchor) {
        if (String(commitmentAnchor.height) !== c.anchor.height) refuse("commitment_mismatch", "the ledger entry's OTS proof anchors at height " + commitmentAnchor.height + ", the record says " + c.anchor.height);
        if (commitmentAnchor.hash && String(commitmentAnchor.hash).toLowerCase() !== String(c.anchor.hash).toLowerCase()) refuse("commitment_mismatch", "the anchor block hash the reader verified is not the one in the record");
      }
    }
    if (pool) {
      try {
        const re = await drawWitnesses({ pool, beaconHash: d.beacon.hash, subjectSha256: d.subject_sha256, k: d.k, excludeHost: own || undefined });
        if (re.pool_sha256 !== d.pool_sha256) refuse("pool_mismatch", "the pool given to the verifier hashes to " + re.pool_sha256 + ", the record says " + d.pool_sha256);
        else if (canonicalUtf8(re.drawn) !== canonicalUtf8(drawn)) refuse("draw_mismatch", "recomputing the draw from beacon, pool and subject gives [" + re.drawn.join(", ") + "], the record says [" + drawn.join(", ") + "]");
        else if (re.pool_size !== d.pool_size) refuse("draw_mismatch", "draw.pool_size " + d.pool_size + " is not the size of the pool given (" + re.pool_size + ")");
      } catch (e) { refuse("bad_pool", "the pool given to the verifier is malformed: " + String(e && e.message || e)); }
    }
  }
  let poolByDomain = null;
  if (pool) { try { poolByDomain = new Map(normalizePool(pool).map((e) => [e.signed_domain.toLowerCase(), e])); } catch { poolByDomain = null; } }
  const answered = [], agreeing = [], disagreeing = [];
  const ext = Array.isArray(verify.external) ? verify.external : [];
  for (let n = 0; n < ext.length; n++) {
    const e = ext[n]; if (!e || !e.record) continue;   // v0 の自由形 (Agenstry の行など) は数えん、拒否もせん
    const rec = e.record, tag = "external[" + n + "]";
    const v = await verifyRecord(rec);
    if (!v.ok) { for (const x of v.refusals) refuse(x.code, tag + ": " + x.why); continue; }
    if (rec.schema !== SCHEMAS.observation) { refuse("bad_external", tag + ": record is " + rec.schema + ", not " + SCHEMAS.observation); continue; }
    if (!rec.signature_ed25519_b64 || !rec.public_key_ed25519_b64) { refuse("witness_unsigned", tag + ": an embedded observation must be signed"); continue; }
    const dom = String(rec.source.signed_domain).toLowerCase();
    if (dom !== String(e.signed_domain).toLowerCase()) { refuse("witness_domain_mismatch", tag + ": record is signed for " + rec.source.signed_domain + ", entry says " + e.signed_domain); continue; }
    if (own && dom === own) { refuse("self_witness", tag + ": the endpoint's own host witnessed itself (11.4)"); continue; }
    if (!drawn.some((x) => String(x).toLowerCase() === dom)) { refuse("witness_not_drawn", tag + ": " + rec.source.signed_domain + " was not drawn"); continue; }
    if (endpoint && hostOf(rec.endpoint) !== hostOf(endpoint)) { refuse("witness_endpoint_mismatch", tag + ": observation is about " + rec.endpoint + ", the segment is about " + endpoint); continue; }
    if (d && rec.request_sha256 !== d.request_sha256) { refuse("witness_request_mismatch", tag + ": observation answers request " + rec.request_sha256 + ", the draw sent " + d.request_sha256); continue; }
    if (executionAt && rec.recorded_at < executionAt) { refuse("witness_before_execution", tag + ": observation recorded_at " + rec.recorded_at + " is before the execution " + executionAt + " it is supposed to re-verify"); continue; }
    if (poolByDomain) {
      const pe = poolByDomain.get(dom);
      if (!pe || pe.public_key_ed25519_b64 !== rec.public_key_ed25519_b64 || pe.key_url !== rec.source.key_url) { refuse("witness_key_mismatch", tag + ": signed with a key or key_url that is not the pool's for " + rec.source.signed_domain); continue; }
    }
    answered.push(rec.source.signed_domain);
    if (agreeing.includes(dom) || disagreeing.includes(dom)) continue;   // 一 domain 一票 (11.4 counting)
    (subsetMatches(verify.expected_after, rec.observed) ? agreeing : disagreeing).push(dom);
  }
  if (q !== null && verify.recovered === true && agreeing.length < q) refuse("witness_quorum_short", "recovered is true but " + agreeing.length + " of the required " + q + " drawn witnesses observed the expected state (drawn " + drawn.length + ", answered " + answered.length + ", disagreeing " + disagreeing.length + ")");
  return { refusals, drawn: drawn.slice(), answered, agreeing, disagreeing };
}

// 連鎖 (1 事故 = 1 区間) の検証。records は記録順。
// opts.operatorKeys: 運営者の公開鍵 (base64 raw Ed25519) の配列。渡すと strict モード (v1):
//   人間承認プリミティブ (approval: human) の実行は、その許可が運営者鍵で署名され、かつ鍵が信用集合に在ることを要求する。
//   渡さんと lenient (v0 互換): decision: approved だけで通す。既存の記録を割らんため。
// opts.witnessQuorum: { q, k, pool, beaconHash, requireCommitment, commitmentAnchor } (v2, v2.2)。渡すと verify に q 人の籤証人の一致を要求する。k は方針の引く数 (運営者が短く引き直すのを許さん)。渡さんでも、
//   verify に draw か埋め込み観測が在れば、その中身の整合 (署名、身元、引かれとるか) は見る。
export async function verifyChain(records, opts = {}) {
  const operatorKeys = Array.isArray(opts.operatorKeys) ? opts.operatorKeys : null;
  const witnessQuorum = opts.witnessQuorum && typeof opts.witnessQuorum === "object" ? opts.witnessQuorum : null;
  const refusals = [];
  const refuse = (code, why) => refusals.push({ code, why });
  if (!Array.isArray(records) || records.length === 0) { refuse("empty_chain", "no records"); return { ok: false, refusals }; }

  const hashes = [];
  for (let i = 0; i < records.length; i++) {
    const v = await verifyRecord(records[i]);
    if (!v.ok) { for (const x of v.refusals) refuse(x.code, "record[" + i + "] (" + (records[i] && records[i].schema) + "): " + x.why); return { ok: false, refusals }; }
    hashes.push(v.record_sha256);
  }

  let i = 0; const drifts = [];
  while (i < records.length && records[i].schema === SCHEMAS.drift) { drifts.push(hashes[i]); i++; }
  if (drifts.length === 0) { refuse("no_drift", "a segment starts with at least one drift record"); return { ok: false, refusals }; }

  const rest = records.slice(i);
  const expect = [SCHEMAS.proposal, SCHEMAS.authorization, SCHEMAS.execution, SCHEMAS.verify];
  if (rest.length > expect.length) refuse("bad_order", "more than " + expect.length + " records after the drift records");
  for (let k = 0; k < Math.min(rest.length, expect.length); k++) {
    if (rest[k].schema !== expect[k]) refuse("bad_order", "record[" + (i + k) + "] is " + rest[k].schema + ", expected " + expect[k]);
  }
  if (refusals.length) return { ok: false, refusals };

  for (let k = i; k < records.length; k++) {
    if (records[k].prev !== hashes[k - 1]) refuse("chain_broken", "record[" + k + "].prev " + records[k].prev + " != previous record_sha256 " + hashes[k - 1]);
  }
  const [proposal, authorization, execution, verify] = rest;
  if (proposal) for (const h of proposal.drift_sha256) if (!drifts.includes(h)) refuse("unknown_drift", "proposal cites drift " + h + " that is not in this segment");
  if (authorization && authorization.proposal_sha256 !== hashes[i]) refuse("ref_mismatch", "authorization.proposal_sha256 != proposal record_sha256");
  if (execution && execution.authorization_sha256 !== hashes[i + 1]) refuse("ref_mismatch", "execution.authorization_sha256 != authorization record_sha256");
  if (verify && verify.execution_sha256 !== hashes[i + 2]) refuse("ref_mismatch", "verify.execution_sha256 != execution record_sha256");
  if (authorization && execution && authorization.decision !== "approved") refuse("unauthorized_execution", "execution follows an authorization whose decision is " + authorization.decision);
  if (execution) {
    const prim = execution.primitive;
    const needsHuman = !!(PRIMITIVES[prim] && PRIMITIVES[prim].approval === "human");
    if (needsHuman && operatorKeys) {
      if (!authorization) refuse("unauthorized_execution", "human-approval primitive " + prim + " executed with no authorization");
      else {
        const signed = !!(authorization.signature_ed25519_b64 && authorization.public_key_ed25519_b64);
        if (!signed) refuse("authorization_unsigned", "human-approval primitive " + prim + " follows an authorization not signed by an operator key");
        else if (!operatorKeys.includes(authorization.public_key_ed25519_b64)) refuse("authorization_untrusted_key", "authorization signed by a key not in the operator trust set");
      }
    }
    if (authorization && authorization.expires_at && execution.recorded_at > authorization.expires_at) refuse("authorization_expired", "execution.recorded_at " + execution.recorded_at + " is after authorization.expires_at " + authorization.expires_at);
  }
  if (proposal && execution && proposal.primitive !== execution.primitive) refuse("primitive_mismatch", "execution.primitive " + execution.primitive + " != proposal.primitive " + proposal.primitive);
  if (proposal && verify && canonicalUtf8(proposal.expected_after) !== canonicalUtf8(verify.expected_after)) refuse("expected_after_drift", "verify.expected_after differs from proposal.expected_after: the target moved after authorization");
  if (verify && verify.recovered === true) {
    // recovered:true を名乗るなら、observed が expected_after の全 surface を持っとらなあかん
    for (const k of Object.keys(verify.expected_after)) if (!(k in verify.observed)) refuse("recovered_unobserved", "recovered is true but observed has no entry for surface " + k);
  }
  let witness = null;
  if (verify && (witnessQuorum || verify.draw !== undefined || (Array.isArray(verify.external) && verify.external.some((e) => e && e.record)))) {
    witness = await verifyWitnesses(verify, { ownHost: hostOf(records[0].endpoint), endpoint: records[0].endpoint, executionSha256: hashes[i + 2], executionAt: execution && execution.recorded_at, quorum: witnessQuorum });
    for (const x of witness.refusals) refuse(x.code, x.why);
  }
  return { ok: refusals.length === 0, refusals, segment: { drifts, hashes, complete: rest.length === 4, ...(witness ? { witness: { drawn: witness.drawn, answered: witness.answered, agreeing: witness.agreeing, disagreeing: witness.disagreeing } } : {}) } };
}

// 信用アンカーを gate から取る (0.4.8 の /keys/operator.json)。404 = まだ配っとらん = 空の集合 (strict は全部 authorization_untrusted_key になる。それが正しい)。
// これで第三者の流れは 1 行: verifyChain(records, { operatorKeys: await fetchOperatorKeys(origin) })
export async function fetchOperatorKeys(origin) {
  const r = await fetch(String(origin).replace(/\/+$/, "") + "/keys/operator.json", { headers: { "user-agent": "recovery-verify/" + VERIFIER_VERSION }, signal: AbortSignal.timeout(15000) });
  if (r.status === 404) return [];
  if (!r.ok) throw new Error("operator key route answered http " + r.status);
  const j = await r.json();
  return j && typeof j.public_key_ed25519_b64 === "string" && j.public_key_ed25519_b64.trim() ? [j.public_key_ed25519_b64.trim()] : [];
}


// ---- internal import aliases (restored from stripped aliased imports) ----
const drawWitnesses = draw;

// ---- CLI ----
function tsugiArgs(argv) {
  const a = {}; const pos = [];
  for (let i = 0; i < argv.length; i++) { const x = argv[i]; if (x.startsWith("--")) { const v = argv[i + 1]; if (v !== undefined && !v.startsWith("--")) { a[x.slice(2)] = v; i++; } else a[x.slice(2)] = true; } else pos.push(x); }
  return { a, pos };
}
async function tsugiMain() {
  const { a, pos } = tsugiArgs(process.argv.slice(2));
  const file = pos[0];
  if (!file) { console.error("usage: node tsugi_verify.mjs chain.json [--operator-key <b64> | --fetch-operator-key <origin>] [--pool pool.json --q N --k N --beacon <hash> --require-commitment --anchor-height H --anchor-hash <hash>]"); process.exit(2); }
  const loaded = JSON.parse(readFileSync(file, "utf8"));
  const records = Array.isArray(loaded) ? loaded : loaded.records;
  const opts = {};
  if (a["operator-key"]) opts.operatorKeys = String(a["operator-key"]).split(",").map((s) => s.trim()).filter(Boolean);
  else if (a["fetch-operator-key"]) opts.operatorKeys = await fetchOperatorKeys(a["fetch-operator-key"]);
  else if (!Array.isArray(loaded) && typeof loaded.operator_public_key_ed25519_b64 === "string" && a["trust-embedded-key"]) opts.operatorKeys = [loaded.operator_public_key_ed25519_b64];
  if (a.pool || a.q || a.k || a.beacon || a["require-commitment"] || a["anchor-height"]) {
    opts.witnessQuorum = {};
    if (a.pool) opts.witnessQuorum.pool = JSON.parse(readFileSync(a.pool, "utf8"));
    if (a.q) opts.witnessQuorum.q = Number(a.q);
    if (a.k) opts.witnessQuorum.k = Number(a.k);
    if (a.beacon) opts.witnessQuorum.beaconHash = String(a.beacon);
    if (a["require-commitment"]) opts.witnessQuorum.requireCommitment = true;
    if (a["anchor-height"]) opts.witnessQuorum.commitmentAnchor = { height: String(a["anchor-height"]), ...(a["anchor-hash"] ? { hash: String(a["anchor-hash"]) } : {}) };
  }
  const report = await verifyChain(records, opts);
  const out = { verifier: "tsugi_verify " + VERIFIER_VERSION, mode: { operator_keys: opts.operatorKeys ? opts.operatorKeys.length : 0, witness_quorum: opts.witnessQuorum || null }, ...report,
    note: opts.operatorKeys ? undefined : "lenient: no operator key given, so a chat-approved (unsigned) authorization passes; pass --operator-key or --fetch-operator-key <origin> for strict",
    does_not_establish: ["that any record is true: hashes and signatures prove who wrote what and in which order, not that the observation was correct", "that the repair was the right one: that is the proposal's own does_not_establish", "operator independence of the witness that wrote the drift records: read witness.vantage"] };
  console.log(JSON.stringify(out, null, 2));
  process.exit(report.ok ? 0 : 1);
}
let tsugiIsMain = false;
try { tsugiIsMain = process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url); } catch (e) { tsugiIsMain = false; }
if (tsugiIsMain) await tsugiMain();
