/**
 * 見張る先の台帳。足すのはここに1件足すだけ。
 * kind:
 *   list      : HTML の一覧頁。<a> の (URL, 文字) の集合を前回と比べ、増えたものを出来事にする
 *   rss       : RSS/RDF。item の (link, title) の集合を比べる
 *   egov_law  : e-Gov 法令API v2 /laws?law_id= 。現行版の law_revision_id と、施行前の改正予定を見る
 *   egov_revs : e-Gov 法令API v2 /law_revisions/{law_id} 。まだ施行されていない改正(公布済み)を先に拾う
 *   kanpo     : 官報の当日の目次。keywords に当たる行だけを出来事にする
 *   text      : 本文の頁(法令等データベースの統合版)。title_must で題名を確かめてから本文のハッシュを比べる
 *   probe     : 次に出るはずの URL を HEAD で叩き、出たら出来事にする(単価表の翌月版など)
 * domain: nursing(JHNRD) / construction(JCCDB)
 * impacts: 当たったとき候補に挙げる JHNRD の項目 id。keyword -> ids の対応は impact.js。
 *
 * URL は 2026-09-26 に取れたものだけを載せている(取れなかったものは載せない)。
 */
export const SOURCES = [
  // ---------------- 訪問看護(医療・介護) ----------------
  { id: "mhlw-shinryo-r8-tsuchi", domain: "nursing", kind: "list",
    title: "令和8年度診療報酬改定について(告示・通知・疑義解釈・訂正事務連絡の一覧)",
    url: "https://www.mhlw.go.jp/stf/newpage_67729.html", link_filter: "\\.pdf$|/content/",
    why: "疑義解釈(その14以降)と訂正事務連絡はここに足される。厚労省の新着 RSS には載らないことを確かめてある(2026-09-26)。" },
  { id: "mhlw-kaigo-saishin", domain: "nursing", kind: "list",
    title: "介護保険最新情報(一覧)",
    url: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/kaigo_koureisha/index_00010.html", link_filter: "\\.pdf$|/content/",
    why: "介護報酬の告示・通知・Q&A はここで配られる。RSS は無い。" },
  { id: "mhlw-kaigo-r8", domain: "nursing", kind: "list",
    title: "令和8年度介護報酬改定について",
    url: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000188411_00073.html", link_filter: "\\.pdf$|/content/" },
  { id: "mhlw-kyufuhi-bunkakai", domain: "nursing", kind: "list",
    title: "社会保障審議会 介護給付費分科会(開催一覧)",
    url: "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126698_00022.html", link_filter: "newpage_|shingi2|/content/",
    why: "令和9年度介護報酬改定の議論(2026年10〜12月に具体的方向性、12月にとりまとめ、2027年1月頃に諮問・答申の日程案)。" },
  { id: "mhlw-chuikyo", domain: "nursing", kind: "list",
    title: "中央社会保険医療協議会 総会(開催一覧)",
    url: "https://www.mhlw.go.jp/stf/shingi/shingi-chuo_128154.html", link_filter: "newpage_|shingi2|/content/" },
  { id: "mhlw-news-rss", domain: "nursing", kind: "rss",
    title: "厚生労働省 新着情報 RSS",
    url: "https://www.mhlw.go.jp/stf/news.rdf",
    keywords: ["訪問看護", "診療報酬", "介護報酬", "中央社会保険医療協議会", "介護給付費分科会", "疑義解釈", "算定"] },
  { id: "egov-pubcom-shakaihoken", domain: "nursing", kind: "rss",
    title: "e-Gov パブリック・コメント(社会保険)RSS",
    url: "https://public-comment.e-gov.go.jp/rss/pcm_list_0000000050.xml", keywords: [] },
  { id: "egov-pubcom-shakaifukushi", domain: "nursing", kind: "rss",
    title: "e-Gov パブリック・コメント(社会福祉)RSS",
    url: "https://public-comment.e-gov.go.jp/rss/pcm_list_0000000049.xml", keywords: ["介護", "訪問看護", "居宅サービス"] },
  { id: "egov-houkan-unei-kijun", domain: "nursing", kind: "egov_law",
    title: "指定訪問看護の事業の人員及び運営に関する基準(平成12年厚生省令第80号)",
    url: "https://laws.e-gov.go.jp/api/2/laws?law_id=412M50000100080", law_id: "412M50000100080",
    baseline_note: "2026-09-26 時点の現行 law_revision_id = 412M50000100080_20260601_508M60000100021(令和8年厚生労働省令第21号、2026-06-01 施行)" },
  { id: "egov-kyotaku-kijun", domain: "nursing", kind: "egov_law",
    title: "指定居宅サービス等の事業の人員、設備及び運営に関する基準(平成11年厚生省令第37号)",
    url: "https://laws.e-gov.go.jp/api/2/laws?law_id=411M50000100037", law_id: "411M50000100037",
    impacts: ["genzan-bcp", "genzan-gyakutai"] },
  { id: "egov-houkan-unei-kijun-revs", domain: "nursing", kind: "egov_revs",
    title: "同 省令第80号 の改正履歴(施行前の改正を先に拾う)",
    url: "https://laws.e-gov.go.jp/api/2/law_revisions/412M50000100080", law_id: "412M50000100080" },
  { id: "egov-kyotaku-kijun-revs", domain: "nursing", kind: "egov_revs",
    title: "同 省令第37号 の改正履歴",
    url: "https://laws.e-gov.go.jp/api/2/law_revisions/411M50000100037", law_id: "411M50000100037" },
  { id: "kanpo-today", domain: "nursing", kind: "kanpo",
    title: "官報(当日の目次)",
    url: "https://www.kanpo.go.jp/{YYYYMMDD}/{YYYYMMDD}.fullcontents.html",
    keywords: ["訪問看護", "療養費", "居宅サービス", "介護予防サービス", "介護給付費", "診療報酬の算定方法", "厚生労働大臣が定める基準"],
    why: "告示は e-Gov 法令API に収録されない(law_type に告示が無い)。告示の公布は官報でしか拾えない。令和7年4月から官報は電子版が正本。" },
  { id: "tdoc-kokuji67-genko", domain: "nursing", kind: "text",
    title: "訪問看護療養費に係る指定訪問看護の費用の額の算定方法(告示第67号 現行)",
    url: "https://www.mhlw.go.jp/web/t_doc?dataId=84aa9734&dataType=0&pageNo=1",
    title_must: ["訪問看護療養費に係る指定訪問看護の費用の額の算定方法", "告示第67号"],
    why: "統合版の本文が変われば、告示が改正されたか、DB 側の写しが直されたかのどちらか。どちらでも JHNRD の医療の項目の読み直しが要る。" },
  { id: "tdoc-kokuji19-genko", domain: "nursing", kind: "text",
    title: "指定居宅サービスに要する費用の額の算定に関する基準(告示第19号 現行)",
    url: "https://www.mhlw.go.jp/web/t_doc?dataId=82aa0253&dataType=0&pageNo=1",
    title_must: ["指定居宅サービスに要する費用の額の算定に関する基準", "告示第19号"], section: ["3　訪問看護費", "4　訪問リハビリテーション費"] },
  // [2026-09-26 seed.24] 要件の本文(告示)の統合版。本文が変われば、該当する項目の requirements を読み直す。
  { id: "tdoc-kokuji103-genko", domain: "nursing", kind: "text",
    title: "訪問看護療養費に係る訪問看護ステーションの基準等(告示第103号 現行)",
    url: "https://www.mhlw.go.jp/web/t_doc?dataId=84aa7834&dataType=0&pageNo=1",
    title_must: ["訪問看護療養費に係る訪問看護ステーションの基準等", "告示第103号"],
    impacts: ["iryo-kanri-shonichi", "iryo-kasan-24h", "iryo-hokatsu", "iryo-baseup"],
    why: "機能強化型・24時間対応体制・包括型・ベースアップ評価料の施設基準の本文。" },
  { id: "tdoc-kokuji95-genko", domain: "nursing", kind: "text",
    title: "厚生労働大臣が定める基準(告示第95号 現行)",
    url: "https://www.mhlw.go.jp/web/t_doc?dataId=82ab4584&dataType=0&pageNo=1",
    title_must: ["厚生労働大臣が定める基準(", "告示第95号"],
    impacts: ["kaigo-kasan-kango-taisei", "kaigo-kasan-kinkyuji", "kasan-tokubetsu-kanri", "kasan-terminal", "kaigo-kasan-service-taisei", "genzan-bcp", "genzan-gyakutai"],
    why: "看護体制強化加算・緊急時訪問看護加算・サービス提供体制強化加算・減算の基準。全サービス分の告示なので、訪問看護以外の改正でも変わる(人が振り分ける)。" },
  { id: "tdoc-kokuji94-genko", domain: "nursing", kind: "text",
    title: "厚生労働大臣が定める基準に適合する利用者等(告示第94号 現行)",
    url: "https://www.mhlw.go.jp/web/t_doc?dataId=82ab4583&dataType=0&pageNo=1",
    title_must: ["厚生労働大臣が定める基準に適合する利用者等", "告示第94号"],
    impacts: ["kasan-tokubetsu-kanri", "kasan-terminal"],
    why: "特別管理加算の対象の状態など。全サービス分の告示。" },

  // ---------------- 建設(JCCDB 観測層) ----------------
  { id: "kkr-zairyo-next", domain: "construction", kind: "probe",
    title: "近畿地方整備局 土木工事設計材料単価表(翌月版)",
    url: "https://www-2.kkr.mlit.go.jp/plan/jigyousya/technical_information/gijutsukanri/qgl8vl0000004zj9-att/{YYYY}_{MM}tanka.pdf",
    month_offset: 1,
    why: "2026_09tanka.pdf の命名が月ごとなら、翌月版の公開を HEAD で拾える。命名が変われば 404 のまま(= 拾えない)なので、その時は台帳を直す。" },
  // [2026-09-26 観測層 v2] 各地方機関の設計材料単価表の一覧頁。新しい PDF のリンクが増えたら、次の月(版)の表が出た合図。
  //   obs2_family は観測層 v2 の出典の系統(sources/<family>-*.json)。取り込みは tools/parsers/ の parser を当て直す。
  { id: "ktr-zairyo-list", domain: "construction", kind: "list", obs2_family: "ktr-zairyo",
    title: "関東地方整備局 設計単価(材料)の一覧", url: "https://www.ktr.mlit.go.jp/gijyutu/gijyutu00000041.html", link_filter: "\\.pdf$" },
  { id: "hrr-zairyo-list", domain: "construction", kind: "list", obs2_family: "hrr-zairyo",
    title: "北陸地方整備局 設計単価の一覧", url: "https://www.hrr.mlit.go.jp/gijyutu/index.html", link_filter: "tannka/.*\\.pdf$" },
  { id: "cbr-zairyo-list", domain: "construction", kind: "list", obs2_family: "cbr-zairyo",
    title: "中部地方整備局 設計単価(資材)の一覧(表は複製・電子化禁止。件数だけを持つ)", url: "https://www.cbr.mlit.go.jp/architecture/kensetsugijutsu/unit_price/index.htm", link_filter: "\\.pdf$" },
  { id: "cgr-zairyo-list", domain: "construction", kind: "list", obs2_family: "cgr-zairyo",
    title: "中国地方整備局 設計単価の一覧", url: "https://www.cgr.mlit.go.jp/skill/index.html", link_filter: "tanka/.*\\.pdf$" },
  { id: "skr-zairyo-list", domain: "construction", kind: "list", obs2_family: "skr-zairyo",
    title: "四国地方整備局 公表単価の一覧(表は複製・電子化禁止。件数だけを持つ)", url: "https://www.skr.mlit.go.jp/etc/kouji/04_tanka.html", link_filter: "kohyotanka/.*\\.pdf$" },
  { id: "thr-zairyo-list", domain: "construction", kind: "list", obs2_family: "thr-zairyo",
    title: "東北地方整備局 設計単価の一覧(表は複製・電子化禁止。件数だけを持つ)", url: "https://www.thr.mlit.go.jp/bumon/b00097/k00910/h12-hp/html/rodo/tanka/tanka.files/sheet001.htm", link_filter: "\\.pdf$",
    why: "tanka.htm は frameset でリンクを持たない。リンクは枠の中の tanka.files/sheet001.htm にある(2026-09-26 独立検証 V3)。" },
  { id: "qsr-zairyo-list", domain: "construction", kind: "list", obs2_family: "qsr-zairyo",
    title: "九州地方整備局 工事積算(設計単価)の一覧", url: "https://www.qsr.mlit.go.jp/for_company/kensetu_joho/koujisekisan.html", link_filter: "/content/.*\\.pdf$" },
  { id: "hkd-zairyo-list", domain: "construction", kind: "list", obs2_family: "hkd-zairyo",
    title: "北海道開発局 設計単価の一覧", url: "https://www.hkd.mlit.go.jp/ky/jg/gijyutu/ud49g70000000uh8.html", link_filter: "\\.pdf$" },
  { id: "ogb-zairyo-list", domain: "construction", kind: "list", obs2_family: "ogb-zairyo",
    title: "沖縄総合事務局 労務・資材単価の一覧", url: "https://www.ogb.go.jp/kaiken/koji/007864", link_filter: "\\.pdf$" },
  { id: "nilim-sekou-package-list", domain: "construction", kind: "list", obs2_family: "mlit-sekou-package",
    title: "施工パッケージ型積算方式 標準単価表(国総研)", url: "https://www.nilim.go.jp/lab/pbg/theme/theme2/theme_sekop.htm", link_filter: "sekop/.*\\.(xlsx|pdf)$",
    why: "年度ごとに標準単価表(Excel・PDF)が替わる。工事(layer work)の行の元。" },
  { id: "mlit-gijutsusha-list", domain: "construction", kind: "list", obs2_family: "mlit-gijutsusha",
    title: "設計業務委託等技術者単価", url: "https://www.mlit.go.jp/tec/gyoumu_tanka.html", link_filter: "\\.pdf$" },
  { id: "mlit-deflator-list", domain: "construction", kind: "list", obs2_family: "mlit-deflator-tsuki",
    title: "建設工事費デフレーター", url: "https://www.mlit.go.jp/statistics/details/t-other-2_tk_000362.html", link_filter: "\\.xlsx$",
    why: "毎月末に更新。四半期別・年度別の列ずれの疑い(2026-09-26)が直ったかも、次の版で確かめる。" },
  { id: "mlit-shinei-yosan-list", domain: "construction", kind: "list", obs2_family: "mlit-shinei-yosan",
    title: "官庁営繕 新営予算単価", url: "https://www.mlit.go.jp/gobuild/kijun_touitukijyun_shineiyosantanka.htm", link_filter: "\\.pdf$" },
  { id: "fema-equipment-rates", domain: "construction", kind: "list", obs2_family: "fema-equipment-rates",
    title: "FEMA Schedule of Equipment Rates", url: "https://www.fema.gov/assistance/public/tools-resources/schedule-equipment-rates", link_filter: "equipment-rates.*\\.pdf$" },
  { id: "census-vip-list", domain: "construction", kind: "text", obs2_family: "census-vip-eits",
    title: "Census Construction Spending (VIP)", url: "https://www.census.gov/construction/c30/c30index.html", title_must: ["Construction Spending"],
    why: "取り込みの元(econ_getzippedfile/?programCode=VIP)は URL が毎月同じで、リンクの増減では新しい公表を拾えない。頁の本文(公表日と数字)の変化で拾う(2026-09-26 独立検証 V3)。" },
  { id: "njdot-wavg-list", domain: "construction", kind: "list", obs2_family: "njdot-wavg",
    title: "NJDOT Estimation Support and Historical Statistics", url: "https://dot.nj.gov/transportation/business/aashtoware/estimation.shtm", link_filter: "\\.pdf$" },
  // [2026-09-26 夕 米国の建設費データベース] 取り込んだ出典の一覧頁。リンクは Apify で頁を取り、link_filter が台帳の URL に当たることを確かめた。
  //   bls.gov は利用者を名乗らない取得を断ることがある。届かなければ fail_streak の出来事(instrument)で分かる。
  //   WBDG の UFS 3-701-01(dod-ufc-370101)は頁が JavaScript で描かれ、HTML にリンクが無い(<div id="root"> だけ)。見張れないので載せない。
  //   Davis-Bacon(SAM.gov)は利用規約が自動取得を禁じているので載せない。
  { id: "bls-oews-tables", domain: "construction", kind: "list", obs2_family: "bls-oews",
    title: "BLS OEWS 職種別賃金の表(年版の zip)", url: "https://www.bls.gov/oes/tables.htm", link_filter: "/oes/special-requests/oesm\\d{2}(st|ma|nat)\\.zip$",
    why: "毎年春に前年5月の版(oesmYYst/ma/nat.zip)が足される。台帳 bls-oews-m2025-* の URL に当たる。" },
  { id: "bls-qcew-files", domain: "construction", kind: "list", obs2_family: "bls-qcew",
    title: "BLS QCEW 年平均(産業別)の zip", url: "https://www.bls.gov/cew/downloadable-data-files.htm", link_filter: "/cew/data/files/\\d{4}/csv/\\d{4}_annual_by_industry\\.zip$",
    why: "年の確報が出ると YYYY_annual_by_industry.zip が足される。台帳 bls-qcew-2025-annual の URL に当たる。" },
  { id: "usace-cwccis", domain: "construction", kind: "list", obs2_family: "usace-cwccis",
    title: "USACE 土木工事費指数(CWCCIS)", url: "https://www.nww.usace.army.mil/missions/cost-engineering/cwccis-indices/", link_filter: "publibrary\\.sec\\.usace\\.army\\.mil/api/download|/Portals/28/.*\\.pdf",
    why: "3月末と9月末の半年ごとに表が替わる。台帳 usace-cwccis-2026-03 の URL(publibrary の download)に当たる。" },
  { id: "usace-ep1110", domain: "construction", kind: "list", obs2_family: "usace-ep1110",
    title: "USACE 建設機械の時間単価(EP 1110-1-8)", url: "https://www.nww.usace.army.mil/missions/cost-engineering/ep1110-1-8/", link_filter: "/Portals/28/.*\\.pdf|contentdm\\.oclc\\.org/utils/getfile",
    why: "2年ごとに12地域の表が替わる。新しい版は Region 表のリンクが入れ替わる。" },
  { id: "hud-tdc", domain: "construction", kind: "list", obs2_family: "hud-tdc",
    title: "HUD 公営住宅の総開発費上限(TDC)", url: "https://www.hud.gov/helping-americans/public-indian-housing-capfund", link_filter: "TDC.*\\.pdf$",
    why: "年ごとに YYYY_Units_TDC_Limits.pdf が足される。台帳 hud-tdc-2024 の URL に当たる。" },
  { id: "fta-capital-cost", domain: "construction", kind: "list", obs2_family: "fta-capcost",
    title: "FTA 資本費データベース", url: "https://www.transit.dot.gov/capital-cost-database", link_filter: "/files/docs/.*\\.(csv|accdb|xlsx)$",
    why: "版が替わると CSV と accdb のファイル名が替わる。台帳 fta-capcost-2024-09 の URL に当たる。" },
  { id: "cbr-tokuchou-shizai", domain: "construction", kind: "list", obs2_family: "cbr-tokuchou-shizai",
    title: "中部地方整備局 特別調査(資材)の報告リスト", url: "https://www.cbr.mlit.go.jp/architecture/kensetsugijutsu/unit_price/R8_chousa_tanka.htm", link_filter: "\\.zip$",
    why: "県ごとの zip(list_r8.MM_shizai_*.zip)。月が替われば名前が替わる。台帳 cbr-tokuchou-shizai-r8-08-* の URL に当たる。年度が替わると頁の URL(R8_)も替わるので、そのときは台帳を直す。" },
  { id: "census-bps", domain: "construction", kind: "text", obs2_family: "census-bps",
    title: "Census Building Permits Survey", url: "https://www.census.gov/construction/bps/", title_must: ["Building Permits Survey"],
    why: "取り込みの元(www2.census.gov/econ/bps/ の月次・年次の txt)はファイル名が月で替わるが、一覧頁には出ない。頁の本文(公表日)の変化で拾う。" },
];
